### PR TITLE
reduce matching params in tests to only the necessary ones

### LINKED ISSUE #190: `matching` not needed in config for test of `prioritise_and_diagnose()`
I don't think this section should be needed here

_Originally posted by @jacobvjk in https://github.com/RMI-PACTA/pacta.multi.loanbook/pull/185#discussion_r1825726103_

### PR DESCRIPTION
**Pull request by cjyetman**
- depends on #193
- closes #190

### CODE REVIEW

**Comment by jdhoffa** [comment]
This looks identical to https://github.com/RMI-PACTA/pacta.multi.loanbook/pull/193 ?

**Comment by cjyetman** [comment]
> This looks identical to #193 ?

This was built off of the #193 branch, and "depends" on it, so once #193 is merged the relevant changes here will be minimal/specific

**Comment by jdhoffa** [comment]
> > This looks identical to #193 ?
> 
> This was built off of the #193 branch, and "depends" on it, so once #193 is merged the relevant changes here will be minimal/specific

I think you are missing a commit here then. 
Both #193 and this current PR only have a single commit in them: 
`29303af`

😊

**Comment by cjyetman** [comment]
> > > This looks identical to #193 ?
> > 
> > 
> > This was built off of the #193 branch, and "depends" on it, so once #193 is merged the relevant changes here will be minimal/specific
> 
> I think you are missing a commit here then. Both #193 and this current PR only have a single commit in them: `29303af`
> 
> 😊

oops... it's pushed now https://github.com/RMI-PACTA/pacta.multi.loanbook/pull/195/commits/de321219a6a1730d188343c102e951f2e7785750

**Review by jacobvjk — APPROVED** [review]

**Review by jdhoffa — APPROVED** [review]

**Pull request merged**
