### PR TITLE
fix reference to filepath variable

### PR DESCRIPTION
**Pull request by cjyetman**
is this correct @jacobvjk?

### CODE REVIEW

**Comment by jacobvjk** [comment]
I meant to indicate the name of the parameter from the config file. `output_prepare_dir` is not a variable visible to the user. But it may be better to just paste the actual path.. what's your view on that?

**Comment by cjyetman** [comment]
> I meant to indicate the name of the parameter from the config file. `output_prepare_dir` is not a variable visible to the user. But it may be better to just paste the actual path.. what's your view on that?

got it.... "name of the parameter from the config file" makes more sense

**Review by jacobvjk — COMMENTED** [review]
see comment above. I would not make this change, but maybe we want to display the actual path instead?

**Comment by cjyetman** [comment]
> see comment above. I would not make this change, but maybe we want to display the actual path instead?

maybe the path, but I think for now the key name in the config is appropriate and in line with messages we show to users in other places

**Pull request closed without merging**
