### PR TITLE
set `_R_CHECK_CRAN_INCOMING_` to `TRUE` in CI for more robust testing

### PR DESCRIPTION
**Pull request by cjyetman**
should see similar errors discovered with `devtools::check_win_devel()`

### CODE REVIEW

**Review by jacobvjk — APPROVED** [review]
seems good in principle, but it does not seem to find the bug you addressed in #353 
the other NOTEs are already addressed in #352 so I would expect to see this pass once this is merged and the release branch is updated

**Comment by cjyetman** [comment]
Yeah, I don't necessarily expect to have this merged. I would suggest merging everything else you're gonna merge, then come back here and update this branch and check the test results before running another check_win_devel. 

I don't know why this doesn't trigger the test failure on Windows path / invalid regex. That's what I was going for. Might be additional env vars to set to faithfully replicate what check_win_devel does. If we can sync this up with that, then I would consider merging this.

**Comment by cjyetman** [comment]
@jacobvjk or you could (temporarily?) add this hack to your #352 branch to test it before merging/check_win_devel

**Comment by cjyetman** [comment]
I propose closing this PR and eventually considering merging #365, which would put this CRAN incoming check in its own GH Action, enabling it to be easier to determine when/how it gets triggered, and its much more feature-rich in how it can report issues to us.

**Comment by cjyetman** [comment]
superseded by #365

**Pull request closed without merging**
