### PR TITLE
implement codecov test coverage testing and reporting

### LINKED ISSUE #192: configure for reporting to Codecov
probably needs a new GH Action for running the test coverage report and sending to Codecov

### PR DESCRIPTION
**Pull request by cjyetman**
- closes #192

(there may need to be some follow-up, e.g. adding a `CODECOV_TOKEN` secret and/or adjusting settings on the Codecov site)

### CODE REVIEW

**Comment by cjyetman** [comment]
@jdhoffa @jacobvjk looks like it will not use the org level `CODECOV_TOKEN` secret, so a repo `CODECOV_TOKEN` secret needs to be added (which I do not have adequate permissions for), which can be found here: https://app.codecov.io/gh/RMI-PACTA/pacta.multi.loanbook/config/general

**Comment by jdhoffa** [comment]
> @jdhoffa @jacobvjk looks like it will not use the org level `CODECOV_TOKEN` secret, so a repo `CODECOV_TOKEN` secret needs to be added (which I do not have adequate permissions for), which can be found here: https://app.codecov.io/gh/RMI-PACTA/pacta.multi.loanbook/config/general

Secret added, and `test-coverage` action re-run.

**Review by jdhoffa — APPROVED** [review]
looks good!

**Comment by cjyetman** [comment]
yup, seems to be working now https://app.codecov.io/github/RMI-PACTA/pacta.multi.loanbook/commit/7b4638a1bf4d47584fa0028c20744d2940662f3f/tree/R

**Review by jacobvjk — APPROVED** [review]

**Pull request merged**
